export { default as Navbar } from "./components/Navbar/Navbar";
export { default as IntroSection } from "./Sections/IntroSection/IntroSection";
export { default as EducationSection } from "./Sections/EducationSection/EducationSection";
export { default as CellsSection } from "./Sections/CellsSection/CellsSection";
export { default as CinemaSection } from "./Sections/CinemaSection/CinemaSection";
export { default as GallerySection } from "./Sections/GallerySection/GallerySection";
export { default as Home } from "./pages/Home/Home";
export { default as Footer } from "./components/Footer/Footer";
export { default as Header } from "./components/Header/Header";
